### ISSUE TITLE
List this package at https://gap-packages.github.io/

### ISSUE THREAD

**Issue by olexandr-konovalov** [isadofschi/g2comp#1]
Hi @isadofschi - only two of your packages are listed at https://gap-packages.github.io/, would you like me to add some more? Also, please see the suggestions at https://github.com/isadofschi/smallcancellation/issues/1 about adding them to our regular testing.

**Comment by isadofschi** [comment]
Hi @alex-konovalov !
Thanks, it would be nice to have G2Comp and ITest listed too. I have just made the PRs for the testing, sorry for the delay.

**Comment by olexandr-konovalov** [comment]
Done, thanks!
